# @name login

@clientid={{$dotenv clientid}}
@secret={{$dotenv secret}}

POST https://cloudinfra-gw.portal.checkpoint.com/auth/external
Content-Type: application/json

{
    "clientId": "{{clientid}}",
  "accessKey": "{{secret}}"
}

###


# @name getLogs
POST https://cloudinfra-gw.portal.checkpoint.com/app/laas-logs-api/api/logs_query
Content-Type: application/json
Authorization: Bearer {{login.response.body.data.token}}

{
    "filter": "ci_app_name:\"CloudGuard Application Security\" AND severity:\"Critical\"",
  "limit": 100,
  "pageLimit": 100,
  "timeframe": {
    "startTime": "2024-04-20T05:00:00Z",
    "endTime": "2024-06-30T21:59:59Z"
  },
  "accounts": [
    "72d56f5b-6855-4d69-aa56-26eb9ff611d2"
  ]
}

###

# @name logQuery

@taskId = {{getLogs.response.body.data.taskId}}
GET https://cloudinfra-gw.portal.checkpoint.com/app/laas-logs-api/api/logs_query/{{taskId}}
Content-Type: application/json
Authorization: Bearer {{login.response.body.data.token}}

###

POST https://cloudinfra-gw.portal.checkpoint.com/app/laas-logs-api/api/logs_query/retrieve
Content-Type: application/json
Authorization: Bearer {{login.response.body.data.token}}

{
  "taskId": "{{getLogs.response.body.data.taskId}}",
  "pageToken": "{{logQuery.response.body.data.pageTokens[0]}}"
}
