
# create .env file with the following content

# clientid=YOUR_OWN_API_KEY
# secret=YOUR_OWN_API_SECRET
# auth_url=https://cloudinfra-gw.portal.checkpoint.com/auth/external





# @name login

@clientid={{$dotenv clientid}}
@secret={{$dotenv secret}}

POST https://cloudinfra-gw.portal.checkpoint.com/auth/external
Content-Type: application/json

{
    "clientId": "{{clientid}}",
  "accessKey": "{{secret}}"
}

###


# @name getLogs

#  "cloudService": "CloudGuard AppSec",

POST https://cloudinfra-gw.portal.checkpoint.com/app/laas-logs-api/api/logs_query
Content-Type: application/json
Authorization: Bearer {{login.response.body.data.token}}

{
    "filter": "ci_app_name:\"CloudGuard Application Security\" AND severity:\"Critical\"",
  "limit": 100,
  "pageLimit": 100,
  "timeframe": {
    "startTime": "2024-04-01T05:00:00Z",
    "endTime": "2024-06-30T21:59:59Z"
  },
  "accounts": [
    "1d81c053-490f-460e-993d-284ec143aa42"
  ]
}

###

# @name logQuery

@taskId = {{getLogs.response.body.data.taskId}}
GET https://cloudinfra-gw.portal.checkpoint.com/app/laas-logs-api/api/logs_query/{{taskId}}
Content-Type: application/json
Authorization: Bearer {{login.response.body.data.token}}

###

POST https://cloudinfra-gw.portal.checkpoint.com/app/laas-logs-api/api/logs_query/retrieve
Content-Type: application/json
Authorization: Bearer {{login.response.body.data.token}}

{
  "taskId": "{{getLogs.response.body.data.taskId}}",
  "pageToken": "{{logQuery.response.body.data.pageTokens[0]}}"
}
